code --install-extension asciidoctor.asciidoctor-vscode
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension gruntfuggly.triggertaskonsave
code --install-extension huntertran.huntertran-cursor-align
code --install-extension james-yu.latex-workshop
code --install-extension jeff-hykin.better-cpp-syntax
code --install-extension ms-python.debugpy
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-python.vscode-python-envs
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.cpptools-extension-pack
code --install-extension ms-vscode.cpptools-themes
code --install-extension ms-vscode.makefile-tools
code --install-extension ms-vscode.remote-explorer
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension surfer-project.surfer
code --install-extension telesoho.vscode-markdown-paste-image
code --install-extension teros-technology.teroshdl
code --install-extension tomoki1207.pdf
code --install-extension twxs.cmake
code --install-extension vitaliymaz.vscode-svg-previewer
code --install-extension xaver.clang-format
code --install-extension yo1dog.cursor-align
code --install-extension yzhang.markdown-all-in-one
code --install-extension zokugun.explicit-folding
